problemType: mtsp
problemFiles:
  - mtsp//lust_kroA100.tsp
  - mtsp//lust_kroB100.tsp
  # - mtsp//lust_euclidA100.tsp
  # - mtsp//lust_euclidB100.tsp
  # - mtsp//dimacs_15_a.tsp
  # - mtsp//dimacs_15_b.tsp
  # - mtsp//dimacs_15_c.tsp
repeat: 3
algorithmConfig:
  antsNum: 100
  iterations: 200
  alpha: 2.0
  beta: 3.0
  pheromoneConfig:
    tpe: Basic
    increment: 0.05
    extinction: 0.05