problemType: cvrp
problemFiles:
  - cvrp//A//A-n32-k5.vrp
  # - mtsp//lust_kroA100.tsp
  # - mtsp//lust_kroB100.tsp
  # - mtsp//lust_euclidA100.tsp
  # - mtsp//lust_euclidB100.tsp
  # - mtsp//dimacs_15_a.tsp
  # - mtsp//dimacs_15_b.tsp
  # - mtsp//dimacs_15_c.tsp
repeat: 1
algorithmConfig:
  antsNum: 1000
  iterations: 10
  alpha: 2.0
  beta: 5.0
  pheromoneConfig:
    tpe: Basic
    increment: 0.05
    extinction: 0.05