# tsp
#problemType: tsp
#problemFiles:
#  - mtsp//lust_kroA100.tsp

# mtsp
#problemType: mtsp
#problemFiles:
#  - mtsp//lust_kroA100.tsp
#  - mtsp//lust_kroB100.tsp
  # - mtsp//lust_euclidA100.tsp
  # - mtsp//lust_euclidB100.tsp
  # - mtsp//dimacs_15_a.tsp
  # - mtsp//dimacs_15_b.tsp
  # - mtsp//dimacs_15_c.tsp

# cvrp
problemType: cvrp
problemFiles:
  - cvrp//A//A-n32-k5.vrp

# algorithm
repeat: 1
algorithmConfig:
  antsNum: 100
  iterations: 200
  alpha: 2.0
  beta: 3.0
  pheromoneConfig:
    tpe: Basic
    increment: 0.05
    extinction: 0.05
    minValue: 0.001
    maxValue: 0.999
    pheromoneDimension: -1 # 0 or below means optimization targets count
    takenAntsToPheromoneUpdate: -1 # 0 or below means all ants
    twoDimConfig: # applicable only for TwoDim type
      size: 10
      getType: ExponentialRandom # options: ExponentialRandom, WeightedCombination, PairingCombination
      updateType: PartFromEvaluation # options: PartFromEvaluation, PartFromIndex